### ISSUE TITLE
在tracking_utils文件中缺少文件

### ISSUE THREAD

**Issue by starsky68** [CaptainEven/YOLOV4_MCMOT#13]
@CaptainEven 
再次打扰你了，在tracking_utils文件中缺少文件，比如kalman_filter，是不是直接负值mcmot项目中的tracking_utils文件中的所有相关文件就可以了，还是有什么修改我没注意到吗？

**Comment by CaptainEven** [comment]
@starsky68 是的，相同的文件从MCMOT中拷贝过来就行了，你用的哪个分支？
可以尝试一下No_Upsample分支，这个分支应该是最全面的, 我自己正在跑的分支就是这个，其他的分支可能存在不完善的地方，祝好！

**Comment by CaptainEven** [comment]
@starsky68 不好意思，是我的失误，没有将tracking_utils加入到commit文件中，现在更新了。

**Comment by starsky68** [comment]
> @starsky68 是的，相同的文件从MCMOT中拷贝过来就行了，你用的哪个分支？
> 可以尝试一下No_Upsample分支，这个分支应该是最全面的, 我自己正在跑的分支就是这个，其他的分支可能存在不完善的地方，祝好！

我用的是master分支，上次的问题关于出现越界的问题，是因为解析数据集max_ids_dict，没有出现过的类别解析不了，我通过人为的统计每个类别出现的数目，即总的track id的数目，然后没有出现过的类别使用key对应的value为0，比如0，1，2类中第1类没有出现过，就是{0：4，1：0，2：5}，这样可以解决上次越界的问题，请问，这样的操作不会对结果出现什么影响吧。

**Comment by starsky68** [comment]
> @starsky68 不好意思，是我的失误，没有将tracking_utils加入到commit文件中，现在更新了。

好的，谢谢了，非常感谢你的贡献。
