### ISSUE TITLE
non_max_suppression_with_yolo_inds我没有找到这个函数的相关信息

### ISSUE THREAD

**Issue by starsky68** [CaptainEven/YOLOV4_MCMOT#14]
@CaptainEven 
作者你好，non_max_suppression_with_yolo_inds我没有找到这个函数的相关信息，我得到的pred, pred_yolo_ids都是none，请问non_max_suppression_with_yolo_inds函数，你可以给提供一下吗？

**Comment by CaptainEven** [comment]
@starsky68 好的，我检查下...

**Comment by CaptainEven** [comment]
@starsky68 我看到代码里面有这个函数，在utils/utils.py里面

**Comment by starsky68** [comment]
> @starsky68 我看到代码里面有这个函数，在utils/utils.py里面

在multitracker.py中，的导入是不是有问题，这些导入好像找不到utils中的non_max_suppression_with_yolo_inds函数

from collections import deque

import numpy as np
import torch
import torch.nn.functional as F
from collections import defaultdict

from tracker import matching
from tracking_utils.kalman_filter import KalmanFilter
from tracking_utils.utils import *
from tracking_utils.log import logger

from .basetrack import BaseTrack, MCBaseTrack, TrackState
from models import *
