### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by austinmw** [CaptainEven/YOLOV4_MCMOT#6]
Hi, how does the performance compare to the CenterNet variant? 

Wasn't the anchor boxes a problem addressed in the FairMOT paper?

**Comment by CaptainEven** [comment]
@austinmw Hi,
(1). As for as i tested in my own dataset, the performance is close to each other, and YOLO has a slim advantage in my project. More detailed evaluation will be released in the future.
(2). I 'm not fully agree with the opinion in the FairMOT paper, anchors-based method can be divided into different categories, center-based(like YOLOV3/V4/V5 series), pixel based(like FCOS, ATSS etc.). As for YOLO's grid cell approach, all the acnhors responsible for detecting the object falls into the grid cell share the same center point(which is the center of the grid cell), so i think, in this regard YOLO is as good as center net in the regard of feature aligment.
Hope my experience will help you.
